mode = "dark"

accent = "#e0474f"
selection = "#27402e"
muted = "#7f9382"

background = "#0a1610"
dark_background = "#07110b"
darker_background = "#040a06"
lighter_background = "#182a1e"

foreground = "#e3ecdd"
dark_foreground = "#8ca08e"
light_foreground = "#eef4e8"
bright_foreground = "#f7fbf2"

red = "#cf4a58"
yellow = "#bacb80"
orange = "#cf9a5f"
green = "#4fae6d"
cyan = "#7fc4b2"
blue = "#82aacb"
magenta = "#b48ec0"
brown = "#a5946e"

bright_red = "#e56a76"
bright_yellow = "#ccdc9c"
bright_green = "#6fca8a"
bright_cyan = "#a0d8c8"
bright_blue = "#a4c2dc"
bright_magenta = "#c8abd4"
